name: Metrics Generate 
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * 1" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push: { branches: ["main"] }
jobs:
  metrics-generate:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          output_action: commit
          committer_branch: auto-generate
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: lliei0x
          template: classic
          filename: metrics.lliei0x.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_calendar: no
          # plugin_calendar_limit: 2
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_repositories: yes
          plugin_repositories_featured: golang/go, rust-lang/rust
          plugin_repositories_order: featured, pinned, starred, random
          plugin_stars: no
          plugin_stars_limit: 3
